### ISSUE TITLE
FAIL tučně

### ISSUE THREAD

**Issue by rodlukas** [cvut/filabel#1]
podle screenshotu má být FAIL tučně, v textu je ale napsáno, že tučně má být jen OK

**Comment by hroncok** [comment]
V textu je napsáno, že Ok má být tučně a dále je napsáno, že místo zeleného OK se vypíše červené FAIL. Tučnost tedy není explicitně zmíněná, ale rozhodně nikde není napsáno, že tučně má být jen OK.

Napíšu to tam ale explicitně. Díky za report.
