### ISSUE TITLE
Setting of web application

### ISSUE THREAD

**Issue by MartinMalyMM** [cvut/filabel#14]
It was required to use options --base --state (and -d/-D as was asked before) and specify reposlugs in the first basic filabel script. I would like to ask you - is this required also for the web application? (I know that the new script executed in shell must work the same as it was, I ask only regarding the web application). If I understood well - it is not required. Please, is an acceptable solution to specify repos in configuration files (e.g. line repos=something in section [github] in file bla.cfg)? I am not sure...

Sometimes I can see issues or PRs in English, sometimes in Czech, which language is preferable, please? Thank you for the response.

**Comment by hroncok** [comment]
The web app can assume the default -d/-D.

State, base and reposlugs however don't make sense for the web app. Those are only useful where scanning repos. However the web app is just listening to webhooks. Once it receives one, it should try to act. Storing a list of reposlugs doesn't achieve any goal.

(I tend to use English everywhere on GitHub. However I respond to anything I can understand.)

**Comment by hroncok** [comment]
(Not sure if this answers you question, feel free to close if yes or ask more specific things in return.)

**Comment by MartinMalyMM** [comment]
Thank you for your response, now I understand more what the web app should do. Previously I thought wrongly that there should be displayed similar output as from the application executed from command line, too...
