### ISSUE TITLE
Modular - test_install: could not read from remote repository

### ISSUE THREAD

**Issue by soucevi1** [cvut/filabel#16]
Při `test_install` (GitHub i PyPI) neprocházím, assert mi v sekci `Clone tests (test installed filabel)` hlásí toto:

```
 AssertionError: Cloning tests from git@github.com:MarekSuchanek/filabel was not successful: Cloning into 'tests'...
E         ERROR: Repository not found.
E         fatal: Could not read from remote repository.
E         
E         Please make sure you have the correct access rights
E         and the repository exists.
E         
E       assert False
E        +  where False = <conftest.ShellExecutionResult object at 0x7ff35cfe32e8>.was_successful
```

Je to chyba, nebo mám repo `git@github.com:MarekSuchanek/filabel` v `test_config.cfg` přepsat na svoje, i když to už je v té proměnné prostředí?

**Comment by rodlukas** [comment]
Stejný problém, přepsání na vlastní repozitář ale i tak nepomůže, protože pak samozřejmě testy spadnou na hledání souboru s autorizačními údaji, který v repozitáři není

**Comment by hroncok** [comment]
Pomůže https://github.com/cvut/filabel/pull/17 ?

**Comment by rodlukas** [comment]
> 
> 
> Pomůže #17 ?

Pomohlo

**Comment by hroncok** [comment]
Díky. Omlouvám se za chybku.

**Comment by dejdy** [comment]
Já mám teda pořád stejný problém:

```
E       AssertionError: Cloning tests from git@github.com:cvut/filabel was not successful: Cloning into 'tests'...
E         git@github.com: Permission denied (publickey).
E         fatal: Could not read from remote repository.
E         
E         Please make sure you have the correct access rights
E         and the repository exists
```
Nějaká rada čím by to mohlo být?

**Comment by hroncok** [comment]
Máš na GitHubu SSH klíč?

**Comment by dejdy** [comment]
Nojo, díky. Přeinstalovával jsem před pár dny systém a na tohle jsem zapomněl. Už to funguje :)

**Comment by hroncok** [comment]
Dám tam HTTPS URL raději.

**Comment by hroncok** [comment]
@dejdy @rodlukas Funguje to i s https://github.com/cvut/filabel/pull/18 ?

**Comment by MarekSuchanek** [comment]
Bez SSH klíče by nemělo jít naklonovat ani to vlastní repo... zvlášť když je private.

**Comment by rodlukas** [comment]
> 
> 
> @dejdy @rodlukas Funguje to i s #18 ?

funguje

**Comment by dejdy** [comment]
> @dejdy @rodlukas Funguje to i s #18 ?

Taky potvrzuju, že funguje.
