### ISSUE TITLE
REPO fail nevypisuji nic?

### ISSUE THREAD

**Issue by Ondrysak** [cvut/filabel#4]
> 
> V případě, že nějaký repozitář nelze zpracovat (např. neexistuje), místo zeleného OK se u něj vypíše tučné červené FAIL. Seznam PR u něj logicky nebude.
> 
> V případě, že se štítkování nějaké PR jakkoliv nezdaří, vypíše se také červené FAIL. Pozor, zda máte práva přidat štítky, se dozvíte jedině tak, že ověříte, že se to podařilo. GitHub API vrací při změně štítků i informace o štítkách.
> 
> Barevné výpisy FAIL piště na standardní výstup.
> 

Pokud selže jakýkoliv PR v ramci REPO nevypisuji nic pouze `REPO user/name - FAIL` ?

**Comment by Ondrysak** [comment]
@hroncok

**Comment by hroncok** [comment]
Buďto selže požadavek na seznam PR. Pak se vypíše FAIL u repa a jinak nic.
Nebo selže požadavek na konkrétní PR (např na nastavení labelů) a pak se u repa napíše OK, ale u každého PR bude FAIL. Příklad:

```console
$ python filabel.py --config-labels labels.abc.cfg --config-auth auth.real.cfg hroncok/filabel-testrepo-everybody
REPO hroncok/filabel-testrepo-everybody - OK
  PR https://github.com/hroncok/filabel-testrepo-everybody/pull/36 - FAIL
  PR https://github.com/hroncok/filabel-testrepo-everybody/pull/35 - FAIL
  ...
  PR https://github.com/hroncok/filabel-testrepo-everybody/pull/3 - FAIL
  PR https://github.com/hroncok/filabel-testrepo-everybody/pull/2 - FAIL
  PR https://github.com/hroncok/filabel-testrepo-everybody/pull/1 - FAIL
```
