### ISSUE TITLE
Odstranění štítků - mylná informace

### ISSUE THREAD

**Issue by tstdin** [cvut/filabel#5]
```
--delete-old/--no-delete-old

[skipped] (GitHub API umí nastavit pouze cílový stav štítků, logika je zde na vás.)
```
Remove a label from an issue
https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue

**Comment by hroncok** [comment]
Po jednom to jde. Měli jsme zde na mysli bulkovou úpravu.
