### ISSUE TITLE
Upřesnění chování webové aplikace

### ISSUE THREAD

**Issue by dejdy** [cvut/filabel#7]
Zdravím,
mám dotaz ohledně chování aplikace u druhého úkolu. Aktuálně to mám tak, že na všechny pull-request eventy (kromě přidání/odebrání labelu) reaguje aplikace tím, že přidá filtry pouze na ten konkrétní pull request, s tím, že se chová stejně jako CLI aplikace s `--no-delete-old` přepínačem. Nedochází tak nikdy k procházení všech PR v daném repu. Je to takto správně?

Díky za odpověď.

**Comment by hroncok** [comment]
Neprocházení všech PR je správně. Jestli no delete old nebo delete old, to jsme nedefinovali a je nám to v zásadě jedno. Mně dává větší smysl delete old, ale nezáleží na tom.
